In [1]:
import pandas as pd
import numpy as np
import os

In [3]:
df = pd.read_csv('/Users/aaliyahgritly/Desktop/Bebo Stuff/Projects/Telco IBM Churn Project/Telco Churn Data (ML).csv')

In [3]:
df.head()

,customerid,count,country,state,city,zip_code,lat_long,latitude,longitude,gender,...,churn_flag,tenure_groups,high_value_customer,number_of_services,contract_risk,contract_risk_score,senior_alone_flag,vulnerability_score,monthly_charge_groups,monthly_charge_score
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,1,0-12 Months,0,3,High Risk,2,0,2,Medium,1
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,1,0-12 Months,1,1,High Risk,2,0,1,High,2
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,1,0-12 Months,1,5,High Risk,2,0,1,High,3
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,1,25-48 Months,1,6,High Risk,2,0,0,High,3
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,1,49+ Months,1,6,High Risk,2,0,1,High,3

# MACHINE LEARNING
* Turn the dataset into something a machine learning model can learn from to try to predict whether a customer will churn
* ML models only understand numerical data ex vulnerability_score not categorical data ex contract_risk

1) Define target and features (ML models learn by first taking input (X), then learn relationship, then predict outcome (Y), which is why we seperate target and features or x and y)

In [7]:
target = 'churn_flag' # Define the target variable for modeling (churn)

# y is the target variable (churn), while x contains all the features (charges, services, etc) except the target variable, which will be used for modeling.
X = df.drop(columns = [target])
y = df[target]

2) Encoding (convert categories into numbers), because ML models can only read numbers

In [9]:
# Convert categorical variables into dummy/indicator variables for modeling
X_encoded = pd.get_dummies(x, drop_first = True)

X_encoded.head()

NameError: name 'x' is not defined

3) Train/Test Split splits data into a training set (model learns form it) and a test set which we evaluate the model on.

In [13]:
from sklearn.model_selection import train_test_split # Import the train_test_split function from scikit-learn

# Split the data into training and testing sets (test_size = 0.2 means 20% for testing, 80% for training)
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size = 0.2, random_state = 42)

4) Scaling to normalize numbers because different scales can confuse models, and to avoid data leakage

In [18]:
from sklearn.preprocessing import StandardScaler # Import the StandardScaler for feature scaling

scaler = StandardScaler() # Create an instance of the StandardScaler

X_train_scaled = scaler.fit_transform(X_train) # Learn the scaling parameters from the training data and apply the transformation to the training data
X_test_scaled = scaler.transform(X_test) # Apply the same scaling transformation to the test data (using the parameters learned from the training data)

5) Build first model

In [19]:
from sklearn.linear_model import LogisticRegression 
# LogisticRegression is a commonly used algorithm for binary classification problems, which is suitable for predicting churn (yes/no).

model = LogisticRegression(max_iter = 1000) # Create an instance of the Logistic Regression model with a maximum of 1000 iterations
model.fit(X_train_scaled, y_train) # Fit the model to the training data
# .fit basically means "train the model on the training data" - it learns the relationships between the features and the target variable (churn) based on the training data.

LogisticRegression(max_iter=1000)

6) Make predictions

In [20]:
y_pred = model.predict(X_test_scaled) # Use the trained model to make predictions on the new test data

7) Evaluate Model (very important)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
# The classification_report function provides a detailed report of the precision, recall, f1-score, and support for each class (churn vs no churn) to evaluate the model's performance.
# precision: Of all the customers predicted to churn, how many actually churned? (True Positives / (True Positives + False Positives))
# recall: Of all the customers who actually churned, how many were correctly predicted to churn? (True Positives / (True Positives + False Negatives))
# f1-score: The harmonic mean of precision and recall, providing a single metric that balances both 

# recall matters most, because missing a churn customer (false negative) is more costly than incorrectly predicting a non-churn customer as a churn customer (false positive).

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1009
           1       0.99      0.98      0.98       400

    accuracy                           0.99      1409
   macro avg       0.99      0.99      0.99      1409
weighted avg       0.99      0.99      0.99      1409

Precision: 0.99 means when the model predicts a customer to churn, they are correct 99% of the time  
Recal: 0.98 mean out of all actuall churners, the model catches 98% of them

In [ ]:
print(confusion_matrix(y_test, y_pred)) # Print the confusion matrix to see the counts of true positives, true negatives, false positives, and false negatives

[[1004    5]
 [   8  392]]

- 1004: Predicted No Churn (0), Actual No Churn (0) (True Negatives) - Correctly predicted 1004 customers as not churning ✅
- 8: Predicted No Churn (0), Actual Churn (1) (False Negatives) - 8 customers churned but model missed them
- 5: Predicted Churn (1), Actual No Churn (0) (False Positives) - Predicted 5 customers as churning when they actually did not churn so false alarm
- 392: Predicted Churn (1), Actual Churn (1) (True Positives) - Correctly predicted 392 customers as churning ✅

# Evalute model and move to next step
* The model was cheating as it had access to columns like churn_flag and churn_score, basically giving it the correct answers
* Now we remove the columns and try again

In [4]:
df = pd.read_csv('/Users/aaliyahgritly/Desktop/Bebo Stuff/Projects/Telco IBM Churn Project/Telco Churn Data (ML).csv')

In [5]:
y = df['churn_flag']

In [6]:
features = [
    'gender', 'senior_citizen', 'partner', 'dependents',
    'tenure_months', 'phone_service', 'multiple_lines',
    'internet_service', 'online_security', 'online_backup',
    'device_protection', 'tech_support', 'streaming_tv',
    'streaming_movies', 'contract', 'paperless_billing',
    'payment_method', 'monthly_charges',
    'tenure_groups', 'number_of_services',
    'contract_risk', 'senior_alone_flag',
    'vulnerability_score'
]

X = df[features]

In [7]:
print(X.columns)

Index(['gender', 'senior_citizen', 'partner', 'dependents', 'tenure_months',
       'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charges', 'tenure_groups',
       'number_of_services', 'contract_risk', 'senior_alone_flag',
       'vulnerability_score'],
      dtype='object')

In [8]:
print('churn_flag' in X.columns)

False

In [9]:
X_encoded = pd.get_dummies(X, drop_first=True)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42
)

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [13]:
y_pred = model.predict(X_test_scaled)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.91      0.87      1009
           1       0.70      0.57      0.63       400

    accuracy                           0.81      1409
   macro avg       0.77      0.74      0.75      1409
weighted avg       0.80      0.81      0.80      1409

* Recall 0.57: The model only catches 57% of churners, or misses 43% of customers who will churn.
* Accuracy 0.81: 81% accuracy looks good, but thats only because most customers stay.

* Recall vs Precision: Higher precision usually means fewer false alarms, but misses more churners, while higher recall catches more churners, but more false alarms
* The model is good at identifying non-churners, but struggling to catch churners.

In [15]:
confusion_matrix(y_test, y_pred)

array([[914,  95],
       [173, 227]])

* 914 predicted to not churn, and actually didnt churn ✅
* 173 predicted to not churn, but actually churned
* 95 predicted to churn, but did not churn
* 227 predicted to churn, and actually churned ✅

* The model misses churners because churn behaviour is complicated, not every customer churns for the same reason. Some churn because of pricing, others because of customer service, and others because competitors offered better deals. Also, some churn signals like gender, city, partner, etc maybe weak indicators of churn, so the model gets more noisy information.
* Businesses prefer a higher recall becuase missing churners means losing revenue. So, even if precision is 50%, but recall is 90%+, this accurately predicts churners but many false alarms, which isnt that bad.

## Improving the model
* There is a class imbalance in the data. The model is biased to non-churners, as the dataset has much more non-churners than churners.
* We have to make the model pay extra attention to churn customers as they are fewer.

In [ ]:
from sklearn.linear_model import LogisticRegression 
model = LogisticRegression(max_iter = 1000, class_weight = 'balanced') 
# class_weight = 'balanced' tells the model to automatically adjust the weights of the classes (churn vs no churn) to handle any imbalance in the target variable, which can help improve performance when one class is much more frequent than the other.

model.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [17]:
y_pred = model.predict(X_test_scaled)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.74      0.81      1009
           1       0.55      0.81      0.66       400

    accuracy                           0.76      1409
   macro avg       0.73      0.77      0.74      1409
weighted avg       0.81      0.76      0.77      1409

In [19]:
confusion_matrix(y_test, y_pred)

array([[746, 263],
       [ 76, 324]])

* Recall: Previous model was 57%, now its 81%, so that is very good, but the cost is that precision decreased so there many more fals positives (more loyal customers are incorrectly flagged as churn risks)

# Why is the model predicitng churn?

In [ ]:
coefficients = pd.DataFrame({
    'Feature': X_encoded.columns,
    'Coefficient': model.coef_[0]
})
# this creates a df called coefficients with two columns: 'Feature' and 'Coefficient'
# model.coef_ is an array of shape (1, n_features) containing the coefficients for each feature in the logistic regression model. We take the first row (model.coef_[0]) to get the coefficients for our features and create a DataFrame to easily analyze and sort them.
# A positive coefficient means churn likelihood increases as the feature value increases, while a negative coefficient means churn likelihood decreases as the feature value increases.
coefficients = coefficients.sort_values(
    by='Coefficient',
    ascending=False
)
# this sorts the coefficients DataFrame in descending order based on the 'Coefficient' column, so that the features with the highest positive impact on churn are at the top and those with the most negative impact are at the bottom.
coefficients.head(15)

                            Feature  Coefficient
12     internet_service_Fiber optic     0.310799
7                       partner_Yes     0.215707
28            paperless_billing_Yes     0.177396
1                   monthly_charges     0.161725
11               multiple_lines_Yes     0.149116
30  payment_method_Electronic check     0.141390
4               vulnerability_score     0.131109
34         tenure_groups_49+ Months     0.125850
23                 streaming_tv_Yes     0.102024
25             streaming_movies_Yes     0.095733
10  multiple_lines_No phone service     0.065131
3                 senior_alone_flag     0.033604
19            device_protection_Yes     0.011600
2                number_of_services     0.006885
5                       gender_Male    -0.014211

* Some of these make sense like fiber optic customers (pay more, expect more), paperless billing (more digitally engaged, easier to switch providers), electronic check (manually make electronic payments instead of automated billing), and monthly charges (higher monthly charge = higher churn possibility).
* Some dont make sense, like having a partner. The model isnt saying having a partner causes churn, but that in THIS dataset, partnered customers correlate slightly with churn. Also, parterned customers maybe using fiber internet more, have higher monthly charges, etc.

In [21]:
coefficients.tail(15)

                                   Feature  Coefficient
16       online_backup_No internet service    -0.041566
13                     internet_service_No    -0.041566
14     online_security_No internet service    -0.041566
29  payment_method_Credit card (automatic)    -0.046872
9                        phone_service_Yes    -0.065131
33              tenure_groups_25-48 Months    -0.110993
21                        tech_support_Yes    -0.116926
36               contract_risk_Medium Risk    -0.138796
26                       contract_One year    -0.138796
15                     online_security_Yes    -0.156051
32              tenure_groups_13-24 Months    -0.163615
27                       contract_Two year    -0.342873
35                  contract_risk_Low Risk    -0.342873
8                           dependents_Yes    -0.556582
0                            tenure_months    -0.977979

# These tell us that there are redundant features that are confusing the model like having both tenure groups and tenure months, so we remove them and try again.

In [4]:
features = [
    'gender', 'senior_citizen', 'partner', 'dependents',
    'tenure_months', 'phone_service', 'multiple_lines',
    'internet_service', 'online_security', 'online_backup',
    'device_protection', 'tech_support', 'streaming_tv',
    'streaming_movies', 'contract', 'paperless_billing',
    'payment_method', 'monthly_charges',
    'number_of_services', 'senior_alone_flag',
    'vulnerability_score'
]

X = df[features]

In [5]:
X_encoded = pd.get_dummies(X, drop_first=True)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42
)

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [13]:
y_pred = model.predict(X_test_scaled)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.73      0.81      1009
           1       0.54      0.80      0.65       400

    accuracy                           0.75      1409
   macro avg       0.72      0.77      0.73      1409
weighted avg       0.80      0.75      0.76      1409

In [15]:
confusion_matrix(y_test, y_pred)

array([[741, 268],
       [ 81, 319]])

In [16]:
coefficients = pd.DataFrame({
    'Feature': X_encoded.columns,
    'Coefficient': model.coef_[0]
})

coefficients = coefficients.sort_values(
    by='Coefficient',
    ascending=False
)
coefficients.head(15)

                            Feature  Coefficient
12     internet_service_Fiber optic     0.312413
7                       partner_Yes     0.207717
28            paperless_billing_Yes     0.173056
1                   monthly_charges     0.152126
30  payment_method_Electronic check     0.150976
11               multiple_lines_Yes     0.141346
4               vulnerability_score     0.131522
23                 streaming_tv_Yes     0.102167
25             streaming_movies_Yes     0.098906
10  multiple_lines_No phone service     0.062127
3                 senior_alone_flag     0.030093
19            device_protection_Yes     0.005181
2                number_of_services     0.002305
31      payment_method_Mailed check     0.001089
5                       gender_Male    -0.011334

# Test Tree-Bases models like Random Forest for comparison
* Random forest is less sensitive to scaling and often performs better than LogisticRegression

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
rf_model = RandomForestClassifier(n_estimators = 100, random_state = 42, class_weight = 'balanced')

rf_model.fit(X_train, y_train) # Use X_train NOT X_train_scaled because Random Forests do not require feature scaling.

RandomForestClassifier(class_weight='balanced', random_state=42)

In [19]:
rf_pred = rf_model.predict(X_test)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, rf_pred))
print(confusion_matrix(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.82      0.90      0.86      1009
           1       0.66      0.51      0.57       400

    accuracy                           0.79      1409
   macro avg       0.74      0.70      0.72      1409
weighted avg       0.78      0.79      0.78      1409

[[906 103]
 [198 202]]

# Model Tuning 
* Using probabilities instead of predictions (you will get probability of churn ex 0.82 instead of yes/no)

In [ ]:
# model.predict_proba(X_test_scaled) predicts how likely a customer is to churn
# [:, 1] returns only the probabilities of churn (the second column of the output, where the first column would be the probability of not churning)
# All results are stored in the variable y_probs
y_probs = model.predict_proba(X_test_scaled)[:, 1]

In [ ]:
import numpy as np

# Logistic Regression uses 0.5 as default threshold (> 0.5 churn, <= 0.5 no churn) so we changed the threshold to 0.35 to see if it improves recall (catching more churn customers)
# np.where is similar to an if-statement: if p > 0.35, then predict 1 (churn), else predict 0 (no churn)
y_pred_new = np.where(y_probs > 0.35, 1, 0)

In [23]:
print(classification_report(y_test, y_pred_new))
print(confusion_matrix(y_test, y_pred_new))

              precision    recall  f1-score   support

           0       0.95      0.62      0.75      1009
           1       0.49      0.91      0.64       400

    accuracy                           0.71      1409
   macro avg       0.72      0.77      0.69      1409
weighted avg       0.82      0.71      0.72      1409

[[629 380]
 [ 35 365]]

* Recall decreased but precision increased. 
* This results in catching almost every churn customer, but the trade-off is now there are many false alarms